# Generated by Django 4.2.16 on 2025-04-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
