# Generated by Django 5.2 on 2025-05-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(upload_to='media/songs/'),
        ),
    ]
