# Generated by Django 5.2 on 2025-05-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos/'),
        ),
    ]
