# Generated by Django 4.2.16 on 2025-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_playlist_options_playlist_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='playlist',
            table='playlists',
        ),
    ]
